[ themeid = coloros12 ] && theme_name=ColorOS12
[ themeid = default ] && theme_name=MIUI经典
[ themeid = explore ] && theme_name=MIUI探·界
[ themeid = flyme9 ] && theme_name=Flyme9
[ themeid = lrone ] && theme_name=Lrone
[ themeid = luck7 ] && theme_name=Luck7
[ themeid = perfectcurve ] && theme_name=完美曲线
[ themeid = GoldenBeach ] && theme_name=碧海金沙
[ themeid = LightWings ] && theme_name=光之翼
[ themeid = Nebulae ] && theme_name=宇宙之眼
[ themeid = StarrySky ] && theme_name=星夜彩绘
[ themeid = Reconstruction ] && theme_name=来之翼
[ themeid = AmethystLake ] && theme_name=紫晶湖
[ themeid = Aquamarine ] && theme_name=润泽
[ themeid = iOS ] && theme_name=iOS